version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /azure/bootstrap
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /azure/environments/staging
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /gcp/bootstrap
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /gcp/environments/ai-staging
    schedule:
      interval: monthly
