version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /bootstrap
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directory: /environments/staging
    schedule:
      interval: monthly

