resource "azurerm_user_assigned_identity" "application" {
  name                = "id-${var.name_prefix}-app"
  resource_group_name = var.resource_group_name
  location            = var.location
  tags                = var.tags
}

resource "random_password" "postgres" {
  length           = 40
  special          = true
  override_special = "!#$%&*+-=?@^_"
}

resource "random_password" "jwt" {
  length  = 64
  special = false
}

resource "random_password" "mfa_encryption" {
  length  = 64
  special = false
}

resource "azurerm_key_vault" "this" {
  name                       = var.key_vault_name
  resource_group_name        = var.resource_group_name
  location                   = var.location
  tenant_id                  = var.tenant_id
  sku_name                   = "standard"
  rbac_authorization_enabled = true
  purge_protection_enabled   = true
  soft_delete_retention_days = 7
  tags                       = var.tags
}

resource "azurerm_role_assignment" "terraform_key_vault_admin" {
  scope                = azurerm_key_vault.this.id
  role_definition_name = "Key Vault Administrator"
  principal_id         = var.terraform_principal_object_id
}

resource "azurerm_role_assignment" "application_key_vault_reader" {
  scope                = azurerm_key_vault.this.id
  role_definition_name = "Key Vault Secrets User"
  principal_id         = azurerm_user_assigned_identity.application.principal_id
}

resource "azurerm_key_vault_secret" "postgres_password" {
  name         = "postgres-admin-password"
  value        = random_password.postgres.result
  key_vault_id = azurerm_key_vault.this.id
  content_type = "PostgreSQL administrator password generated by Terraform"

  depends_on = [azurerm_role_assignment.terraform_key_vault_admin]
}

resource "azurerm_key_vault_secret" "jwt_signing_key" {
  name         = "jwt-signing-key"
  value        = random_password.jwt.result
  key_vault_id = azurerm_key_vault.this.id
  content_type = "Fiscora JWT signing key generated by Terraform"

  depends_on = [azurerm_role_assignment.terraform_key_vault_admin]
}

resource "azurerm_key_vault_secret" "mfa_encryption_key" {
  name         = "mfa-encryption-key"
  value        = random_password.mfa_encryption.result
  key_vault_id = azurerm_key_vault.this.id
  content_type = "Fiscora MFA secret encryption key generated by Terraform"

  depends_on = [azurerm_role_assignment.terraform_key_vault_admin]
}
