steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - MODEL_REVISION=${_MODEL_REVISION}
      - --tag
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
options:
  machineType: E2_HIGHCPU_8
  diskSizeGb: 100

